baseurl = "/"
languageCode = "en-us"
title = "Thomas Maintenance"
canonifyUrls = "true"
theme = "landing-page-hugo"

[params]
    description = "We Know Stratas"
    custom_css = ["css/local.css"]

[[params.social]]
	title = "email"
	icon = "envelope-o"
	url = "mailto:info@thomasmaintenace.com"

[[params.social]]
	title = "(604) 202-2542"
	icon = ""
	url = "tel:+16042022452"
